const names = {

  sk: {
    male: [`Tomáš`, `Miroslav`, `Július`, `Stanislav`, `Michal`, `Lukas`, `Filip`, `Zoltán`, `Andrej`, `Lukas`, `Branko`, `Maroš`, `Pavel`, `Peter`, `Dalibor`, `Erik`, `Adrián`, `Ľuboš`, `Jaromír`, `Matej`, `Erik`, `Vladimír`, `František`, `Ján`, `Ľubomír`, `Peter`],
    female: [`Michaela`, `Michaela`, `Marta`, `Alžbeta`, `Michaela`, `Helena`, `Monika`, `Júlia`, `Lucia`, `Alina`, `Erika`, `Monika`, `Bozena`, `Dominika`, `Mária`, `Kristína`, `Marianna`, `Agáta`, `Gabriela`, `Miloslava`, `Vlasta`, `Iveta`, `Mária`, `Gabika`, `Marta`, `Monika`, `Veronika`, `Miroslava`, `Mária`, `Zuzana`, `Ľuboslava`, `Dominika`],
  },
  cz: {
    male: [`Radim`, `Erich`, `David`, `Ladislav`, `Jiří`, `Jaromír`, `Venca`, `Tomáš`, `Stanislav`, `Roman`, `Jan`, `Pavel`, `Jan`, `Mikuláš`, `Miroslav`, `Juraj`, `Martin`, `Róbert`, `Marek`, `Daniela`, `Jiří`, `Tomáš`, `Karel`, `Václav`, `Kryštof`, `Jaroslav`, `Filip`, `Jozef`, `Marcel`, `Jaromír`],
    female: [`Lucie`, `Adél`, `Veronika`, `Vendula`, `Iveta`, `Daniela`, `Lucie`, `Marie`, `Viktorie`, `Iveta`, `Ktstýna`, `Barbora`, `Zuzana`, `Michaela`, `Eliška`, `Olina`, `Nikola`, `Zuzana`, `Jana`, `Jana`, `Michaela`, `Hana`, `Klára`, `Lucie`, `Iveta`, `Radka`, `Eliška`, `Martina`, `Lucie`, `Petra`, `Markéta`, `Andrea`, `Jana`, `Jana`, `Magdalena`, `Monika`, `Klapová`, `Lucie`],
  },
  hu: {
    male: [`István`, `András`, `Richard`, `Kristóf`, `István`, `Török`, `László`, `Tamás`, `Daniel's`, `Árpád`, `Tamás`, `Lászloné`, `Norbert`, `Lajos`, `Mezei`, `Györgyné`, `Balázs`, `Balázs`, `Gergely`, `Norbert`, `György`, `Gábor`, `Sándor`, `László`, `Péter`, `Gyula`, `Pál`, `József`, `György`, `Krisztián`, `Mátyás`, `Bálint`, `Róbert`],
    female: [`Lilla`, `Katalin`, `Évi`, `Kati`, `Ágnes`, `Erika`, `Erzsébet`, `Béla`, `Mónika`, `Éva`, `Erika`, `Mária`, `Erika`, `Marika`, `Ágota`, `Mária`, `Judit`, `Anita`, `Edit`, `Anita`, `Erzsébet`, `Angelika`, `Krisztina`, `Attila`, `Radnóti`, `Márta`, `Erika`, `Mónika`, `Zsuzsa`, `Kürti`, `Jelcsi`, `Ágnes`, `Marianna`, `Károlyné`, `Péterné`, `Ildikó`, `Eszter`, `Zsuzsanna`, `Pálné`, `Erzsébet`, `Mónika`, `Mária`, `Gyarmati`, `Gyuláné`, `Szabina`],
  },
  lt: {
    male: [`Mihail`, `Cornelii`, `Florin`,
      `Catalin`,
      `Lucian`,
      `Mihnea`,
      `Flaviu`,
      `Alexandru`,
      `Valeriu`,
      `Stasys`, `Gustas`, `Grazvydas`, `Vladas`, `Kasparas`, `Mykolas`, `Juozas`, `Anatolijus`, `Donatas`, `Justas`, `Raimis`, `Tomas`, `Domantas`, `Šarūnas`, `Alex`, `Jonas`, `Petras`, `Kęstas`, `Marijonas`, `Antanas`, `Vytas`, `Irmantas`, `Tautvydas`, `Aidas`, `Tadas`],
    female: [`Michaela`,
      `Raluca`,
      `Florentina`,
      `Cristina`,
      `Loredana`,
      `Valentina`,
      `Irene`,
      `Iulia`,
      `Cristina`,
      `Amalia`,
      `Viktorija`, `Kristina`, `Ramunė`, `Patricija`, `Tatjana`, `Ramunė`, `Regina`, `Erika`, `Milla`, `Ruta`, `Inesa`, `Nida`, `Daina`, `Jurgita`, `Ruth`, `Paulina`, `Greta`, `Dalia`, `Karina`, `Reda`, `Gabrielė`, `Vaiva`, `Kristina`, `Jolita`, `Nijolė`, `Maritė`, `Inga`, `Jolita`, `Loreta`, `Stasė`, `Aistė`, `Rūta `, `Gintarė `, `Ramūnė `],
  },
  ro: {
    male: [
      'Toader liviu',
      'Szabo Imre',
      'Albu Iancu',
      'Axinte Dumitru',
      'Adrian Aurica',
      'Radu Zaim',
      'Liszkai Zoltan',
      'Pascu Doru',
      'Blaga Iosif',
      'Moise Constantin',
      'Moldovan Teodor',
      'Oarza Romeo',
      'Piescu Alimpe',
      'Potop Ioan',
      'Popovici Ivan',
      'Baciș Craciun',
      'Valeriu Vierita',
      'Nechifor Petru',
      'George Chioaru',
      'Radu Dimitriu',
      'Popescu Ion',
      'Vichiriuc Petru',
      'Bakó Albert',
      'Biro Jozsef',
      'Hotfoludi Iacob',
      'Trifan Neculai',
      'Cozmei Mihail',
      'Oniga Onisor',
      'Petre Nicolae',
      'Ionescu ion',
      'Abaza Ionel',
      'Peter Martin',
      'Bursumac lucian',
      'Dan Florica',
      'Dumitrascu Ion',
      'Micu Vasile',
      'Sorin Silaghi',
      'Albert Edit',
      'Zot Florentin',
      'Trandafir Ion',
      'Moater ioan',
      'Borza moise',
      'Mureșan Petru',
      'Rodica Barsan',
      'Herman stefan',
      'Maftei Pavel',
      'Fabris Mircea',
      'Sarkadi Stefan',
      'Vioreanu cristian',
      'Anghel Adrian',
      'Sgandar Stefan',
      'Epure Dănuț',
      'Ion Cazacu',
      'Șimon Daniel',
      'Bogdán Emeseo',
      'Munteanu Vodă',
      'Nicolae Alexandru',
      'Opra Alexandru',
      'Steuer Agnes',
      'Fleser Vasile',
      'Mitu Dan'
    ],
    female: [
      'Dorobantu Elena',
      'Horvat Doina',
      'Nemeș Maria',
      'Rădoi Dana',
      'Sandu Maria',
      'Berea Geta',
      'Motoiu Elena',
      'Ioana Țopan',
      'Colţa Maricica',
      'Bucur luminita',
      'Mihalcea Adriana',
      'Maria Verdes',
      'Badica Mirela',
      'Muntean Gabriela',
      'Spita Ioana',
      'Balulescu Gabriela',
      'Nagy Ilona',
      'Bostan Cristina',
      'Meszaros Magdalena',
      'Popescu Maria',
      'Albu Leonita',
      'Luta Aurel',
      'Dumitru Mihaela',
      'Balabaneanu Stela',
      'Buzlea Elisabeta',
      'Emilia Borcescu',
      'Valeria Mitrofan',
      'Fiera Alexandrina',
      'Crasmaru Aglaia',
      'Mariana Suibea',
      'Bregovranu Liliana',
      'Fritea Maria',
      'Vladoi Adriana',
      'Defta Elena',
      'Nemes Diana',
      'Defta Elena',
      'Floroiu Daniela',
      'Dragomireșcu Emilia',
      'Teodorescu Silvia',
      'Brăzdaru Lavinia',
      'Mares Elena',
      'Dumitrescu Paulina',
      'Rotaru Georgeta',
      'Viorica Lucica',
      'Aldea Eleza',
      'Elena Croitoru',
      'Racoveanu Maria',
      'Vremescu Maria',
      'Corina Stoleriu',
      'Colgiu Rodica',
      'Petre Carmen',
      'Viliga Lelia',
      'Ciuciulea Iuliana',
      'Anca Viorica',
      'Buburuz Rozalia',
      'Anca Daniela',
      'Ciurel Ioana',
      'Basca Maria',
      'Adamache Maria',
      'Paraschiv Georgeta',
      'Marincas Viorica',
      'Brindusa Iuliana',
      'Beleț Florina'
    ],
  },
  pl: {
    male: [`Piotr`, `Krzysztof`, `Andrzej`, `Jan`, `Stanisław`, `Tomasz`, `Paweł`, `Marcin`, `Michał`, `Marek`, `Grzegorz`, `Łukasz`, `Adam`, `Józef`, `Zbigniew`, `Jerzy`, `Mateusz`, `Tadeusz`, `Dariusz`, `Mariusz`],
    female: [`Anna`, `Maria`, `Katarzyna`, `Małgorzata`, `Agnieszka`, `Barbara`, `Krystyna`, `Ewa`, `Elżbieta`, `Zofia`, `Teresa`, `Magdalena`, `Monika`, `Janina`, `Danuta`, `Aleksandra`, `Jadwiga`, `Halina`, `Irena`],
  },
  bg: {
    female: [
      'Анна Тинкова',
      'Соня Борисова',
      'Красимира Стоименова',
      'Гинка Великова',
      'Виктория Михайлова',
      'Дарина Кънчева',
      'Иванка Гочева',
      'Иванка Ковачева',
      'Румяна Йосифова',
      'Виолеъа Димитрова',
      'Галина Костадинова',
      'Емилия Касаджикова',
      'Росица Маринова',
      'Тодора Михова',
      'Красимира Денева',
      'Румяна Попова',
      'Галина Костадинова',
      'Стефанка Баръмова',
      'Лилия Симеонова',
      'Камелия Ананиева',
      'Ангелина Николова',
      'Радка Тюфекчиева',
      'Лили Русинова',
      'Людмила Йосифова',
      'Елена Иванова',
      'Мария Ангелова',
      'Елена Манолова',
      'Стоянка Кулева',
      'Юлиана Христова',
      'Красимира Манахилова',
      'Стефка Петрова',
      'Донка Друмева',
      'Соня Иванова',
      'Теодора Кръстева',
      'Сашо Минчев',
      'Павлина Петрова',
      'Антоанета Ценова',
      'Величка Дудева',
      'Йовка Колева',
      'Ирминия Симова',
      'Атанаска Джостова',
      'Димитринка Кушлева',
      'Мариана Кръстанова',
      'Стоянка Димитрова',
      'Недялка Попова',
      'Радостина Георгиева',
      'Боряна Стоянова',
      'Йона Томова',
      'Недялка Енева',
      'Весела Цветанова',
      'Марияна Иванова',
      'Надка Асеноа',
      'Роза Каменова',
      'Костадинка Латунова',
      'Кети Янчулева',
      'Виолета Бахтарлиева',
      'Мария Тонева',
      'Мариана Владимирова',
      'Галина Георгиева',
      'Илка Караниколова',
      'Надя Василева',
      'Босилка Занева',
    ],
    male: [
      'Даниел Иванов',
      'Огнян Олев',
      'Златко Бакалски',
      'Пейчо Колев',
      'Петър Георгиев',
      'Станислав Станев',
      'Иван Мегданов',
      'Фетие Билял',
      'Стамен Вацов',
      'Йордан Йорданов',
      'Йордан Тошев',
      'Филип Бозов',
      'Ивайло Димитров',
      'Богдан Николов',
      'Николай Николов',
      'Любен Димитров',
      'Димитър Стоичков',
      'Петър Митев',
      'Тодор Лалов',
      'Румен Зарков',
      'Янко Дойчев',
      'Митко Станев',
      'Борислав Георгиев',
      'Панчо Ангелов',
      'Бисер Радев',
      'Тодор Тодоров',
      'Емил Борисов',
      'Величко Любомиров',
      'Димитър Ковачев',
      'Драгомир Николов',
      'Георги Панчев',
      'Георги Ценев',
      'Христо Александров',
      'Димитър Първанов',
      'Вилко Хердинандов',
      'Георги Иванов',
      'Румян Тасев',
      'Живко Матев',
      'Красимир Семов',
      'Иван Велчев',
      'Лъчезар Симеонов',
      'Недялко Недялков',
      'Стоян Минчев',
      'Кирил Асенов',
      'Илия Димитров',
      'Марин Георгиев',
      'Георги Георгиев',
      'Петко Златев',
      'Христо Павлов',
      'Станчо Борисов',
    ],
  },
};

export default names;
